/**
 * LongWoo 首頁文案 — 繁體中文（zh-Hant）
 *
 * 本檔為 zh 語言塊的繁體中文版，用語取捨說明：
 * - 以台灣慣用為主、港台皆通為輔：網路、軟體、電子郵件、上傳/下載/儲存/刪除/複製/貼上、設定、
 *   帳號、即時、狀態、意見回饋、連結、介面、使用者等；維持中性正式書面語，不使用港式口語（俾/嘅）
 *   與過度台式口語（欸/喔）。
 * - 站內行話依 i18n 用詞基線：獸裝、委託、訂單、掉落販售、線上商店、站內信、個人中心、管理後台、
 *   工作台、毛布、取色、毛長、Pantone 參考色；「訊息」用於 message、短訊，「資訊」用於 information。
 * - 「您／你」鏡像 zh 原文：委託、查詢、購物等交易流程使用「您」；角色聊天與設定等對話式情境保留
 *   原文的「你」，維持與簡中版一致的語氣。
 * - 純英文品牌設計詞（英文 kicker）與以 En 結尾的英文副標籤欄位（heroTitleEn / titleEn /
 *   formTitleEn / editTitleEn / dropsEntryTitleEn / peripheryEntryTitleEn、addons 之 nameEn、
 *   benefits 之 labelEn、bubble.signupEn）與 zh 塊完全相同，不另行翻譯。
 * - 含 {name} / {msg} 佔位符的句子保留佔位符，引號一律使用全形「」。
 * - 數字、單位（cm/kg/RMB/JPG/PNG/GIF/WebP/2MB/20M/15000RMB-25000RMB/300/750/8888/
 *   15000RMB-25000RMB/9:00-17:00 等）、href/secondaryHref、value/disabled、addons 順序均不改動；
 *   「周」（時間義）轉為「週」，標點一律全形。
 * - 品牌名 LongWoo、TA 與「龍塢」之中文品牌字樣照常轉換／保留。
 */

import type { Gt2Copy } from "./copy";

export const ZH_HANT_COPY: Gt2Copy = {
  tabs: { agent: "智能體", fursuit: "委託獸裝", shop: "線上商店", check: "查詢", about: "關於" },
  agent: {
    kicker: "LONGWOO · CHARACTER LAB",
    heroTitle: "建立你的角色",
    heroTitleEn: "Create Your Character",
    heroLines: [
      "上傳設定圖，描述角色的個性，免費生成你的專屬角色 AI。",
      "長期的學習與陪伴，可以讓 AI 心智無限逼近於真實狀態。",
      "已被充分訓練的 AI 角色，未來可以被載入實體獸裝。",
    ],
    uploadBtn: "上傳",
    formTitle: "角色設定",
    formTitleEn: "Character Profile",
    avatarHint: "點擊上傳頭像 · JPEG / PNG / GIF / WebP · ≤ 2MB",
    avatarFallback: "頭像",
    changeAvatar: "更換頭像",
    nameLabel: "名字",
    namePh: "幫 TA 取一個名字",
    nicknameLabel: "你的稱呼",
    nicknamePh: "AI 會這樣稱呼你",
    personaLabel: "人設",
    personaPh: "描述 TA 的性格、經歷與說話方式……",
    toneLabel: "語氣風格",
    tonePh: "自訂，或點選預設",
    greetingLabel: "開場白",
    greetingPh: "TA 見到你的第一句話",
    createBtn: "建立角色",
    creating: "建立中…",
    backBtn: "返回",
    errName: "請先幫角色取一個名字",
    errAvatarLarge: "頭像圖片不能超過 2MB",
    errAvatarFormat: "僅支援 JPEG / PNG / GIF / WebP 格式",
    errCreate: "建立失敗，請稍後重試",
    errNetwork: "網路異常，請稍後重試",
    loginHint: "建立角色需要先登入",
    loginPromptText: "建立角色需要先登入，你的設定草稿已儲存，登入後會自動恢復",
    goLogin: "前往登入",
    keepEdit: "繼續編輯",
    tonePresets: ["溫柔", "活潑", "傲嬌", "高冷", "幽默", "可愛", "沉穩", "熱情", "毒舌", "元氣", "慵懶", "神秘"],
    chatMy: "我的角色",
    chatEmpty: "還沒有角色，建立你的第一個角色吧",
    chatCreateFirst: "去建立",
    chatHello: "和 TA 打個招呼吧",
    chatHelloWithName: "和 TA 打個招呼吧 · 叫你「{name}」",
    chatInputPh: "對 TA 說點什麼…",
    chatClearTitle: "清空對話",
    chatClearConfirm: "確定要清空和這個角色的全部對話記錄嗎？",
    errChatLoad: "角色載入失敗，請稍後重試",
    errChatSend: "傳送失敗，請稍後重試",
    errChatClear: "清空失敗，請重試",
    editBtn: "調整設定",
    editTitle: "編輯角色",
    editTitleEn: "Edit Character",
    editSubtitle: "調整 TA 的設定，隨時煥然一新",
    editDelete: "刪除角色",
    editDeleting: "刪除中…",
    editSave: "儲存",
    editSaving: "儲存中…",
    editDeleteConfirm: "確定要刪除角色「{name}」嗎？TA 的全部對話記錄也會一併刪除，此操作無法復原。",
    errEditSave: "儲存失敗，請稍後重試",
    errEditDelete: "刪除失敗，請稍後重試",
    errAvatarUpload: "頭像上傳失敗，請重試",
  },
  fursuit: {
    kicker: "COMMISSION · FULL CUSTOM",
    title: "委託你的獸裝",
    titleEn: "Commission Your Fursuit",
    steps: ["上傳設定圖", "選配內容", "折抵權益", "聯絡方式", "等待估價"],
    deliveryHint: "預計 4-6 週後交付*",
    priceRangeHint: "首次購買價格依照15000RMB-25000RMB區間計算",
    uploadTitle: "上傳設定圖",
    uploadHint: "圖片不超過 20M",
    reupload: "重新上傳",
    remove: "移除",
    addonMicro: "選配 · ADD-ON",
    addonHint: "可複選 · 選中的內容將計入估價",
    addonNone: "無",
    addons: [
      { name: "攜帶式頭包", nameEn: "Head Bag", price: "RMB 300", value: 300 },
      { name: "室內腳", nameEn: "Indoor Feet", price: "RMB 750", value: 750 },
      { name: "Longwoo Vision 視覺增強套件", nameEn: "Vision Kit", price: "RMB 8,888", value: 8888, disabled: true, tag: "暫未上線" },
    ],
    benefitTitle: "第三步：是否行使折抵權益與複購權益",
    benefits: [
      { label: "不使用", labelEn: "None", price: "RMB 0", value: 0 },
      { label: "4年期換購權益", labelEn: "4-Year Trade-in", price: "-RMB 3,000", value: 3000 },
      { label: "複購權益*", labelEn: "Repurchase*", price: "-RMB 2,000", value: 2000 },
    ],
    benefitNote: "*原 象山工作室 的首次委託客戶同享複購權益",
    priceBase: "基礎價格",
    priceAddon: "附加選項",
    priceDiscount: "折抵",
    priceTotal: "合計",
    contactTitle: "第四步：請填寫您的資料與聯絡方式",
    bodyTitle: "身體數據",
    bodyHint: "身高 / 體重為必填 · 其餘選填 · 便於預估尺寸",
    socialLabel: "任意平台可以聯繫到您的帳號（如：Bilibili QQ X...）",
    socialPh: "請輸入您的社群平台帳號",
    nameLabel: "姓名",
    namePh: "請輸入您的姓名",
    emailLabel: "Email",
    emailPh: "your@email.com",
    dims: [
      { key: "height", label: "身高", unit: "cm" },
      { key: "weight", label: "體重", unit: "kg" },
      { key: "chest", label: "胸圍", unit: "cm" },
      { key: "waist", label: "腰圍", unit: "cm" },
      { key: "hip", label: "臀圍", unit: "cm" },
      { key: "shoe", label: "鞋碼", unit: "" },
    ],
    btnPrev: "上一步",
    btnNext: "下一步",
    submitBtn: "提 交",
    submitting: "提交中…",
    submitHint: "提交後我們將進行人工估價，並盡快與您聯繫",
    doneTitle: "第五步：請等待我們的人工估價回覆",
    doneText: "我們將於工作日9:00-17:00回覆報價，並與您進行接下來的溝通",
    orderCodePrefix: "您的訂單代碼：",
    copyBtn: "複製訂單代碼",
    copied: "已複製 ✓",
    queryLink: "查詢進度",
    saveTip: "請妥善保管訂單代碼，用於後續查詢估價與進度",
    errImgRequired: "請先上傳設定圖",
    errImgType: "僅支援圖片檔案",
    errImgLarge: "圖片不能超過 20MB",
    errName: "請輸入姓名",
    errEmail: "請輸入有效的電子郵件地址",
    errDimRequired: "此項未填寫",
    errSubmit: "提交失敗，請稍後重試",
    errNetwork: "網路錯誤，請稍後重試",
    errUploadAlert: "設定圖上傳失敗：{msg}。檔案名稱已隨訂單儲存，您可以稍後登入個人中心補充設定圖，或聯繫客服協助上傳。",
  },
  checkPanel: {
    orderNoLabel: "委託單號",
    orderNoPh: "如 LW20250101001",
    emailLabel: "電子郵件",
    emailPh: "請輸入提交委託時填寫的電子郵件",
    btn: "查詢委託",
    loading: "查詢中…",
    errOrderNoRequired: "請輸入委託單號",
    errEmailRequired: "請輸入電子郵件",
    errEmailInvalid: "請輸入有效的電子郵件地址",
    errQueryFailed: "查詢失敗，請檢查單號與電子郵件是否正確",
    errQueryUnknown: "查詢時發生未知錯誤，請稍後重試",
    customerName: "客戶姓名",
    phone: "聯絡電話",
    email: "電子郵件",
    serviceType: "服務類型",
    notSpecified: "未指定",
    desc: "需求描述",
    designImage: "設定圖",
    designImageMissing: "設定圖上傳未成功，如有疑問請聯繫客服",
    estimateAmount: "估價金額",
    note: "備註：",
    deliveryLink: "交付連結",
    replies: "回覆記錄",
    createdAt: "建立時間",
    agreeEstimate: "同意估價",
    agreeEstimateDesc: "請確認估價金額，同意後工作室將開始處理您的委託。",
    agreeEstimateConfirm: "確認同意此估價？同意後工作室將盡快接單開始製作。",
    agreeSuccess: "已確認估價，工作室將盡快接單開始製作",
    agreeFailed: "確認失敗，請稍後重試",
    agreeWaiting: "您已確認估價，工作室接單後將開始製作，請留意進度更新。",
    status: {
      pending: "待估價",
      estimated: "已估價",
      agreed: "已同意估價",
      accepted: "已接單",
      rejected: "已拒單",
      processing: "處理中",
      delivered: "已交付",
      completed: "已完成",
    },
  },
  shopPanel: {
    dropsEntryKicker: "01",
    dropsEntryTitle: "現貨掉落",
    dropsEntryTitleEn: "DROP FURSUITS",
    dropsEntryDesc: "預設獸裝定期掉落販售，現貨與預售同步開放。無需漫長等待，遇見即是緣分。",
    dropsEntryCta: "進入掉落",
    peripheryEntryKicker: "02",
    peripheryEntryTitle: "龍塢周邊",
    peripheryEntryTitleEn: "LONGWOO MERCH",
    peripheryEntryDesc: "周邊商品籌備中，敬請期待。",
    peripheryEntryCta: "未開放",
    backEntries: "返回商店",
    dropsKicker: "01 / DROP ITEMS",
    dropsHeading: "現貨掉落",
    dropsSub: "成品部分立即交付，剩餘部分預計 4-6 週後交付*",
    loading: "正在載入掉落資訊…",
    empty: "暫無掉落資訊，敬請期待",
    statusOnSale: "發售",
    statusPreparing: "準備",
    statusAdopted: "領養",
    statusOptionOnSale: "發售（可購買）",
    statusOptionPreparing: "準備（僅查看）",
    statusOptionAdopted: "領養（交付中）",
    btnSelect: "選擇",
    btnAdopted: "已被領養",
    btnPreparing: "準備中 · 敬請期待",
    viewImage: "查看完整大圖",
    checkoutKicker: "02 / CHECKOUT",
    checkoutTitle: "確認購買",
    productLabel: "已選掉落",
    nameLabel: "姓名",
    namePh: "請輸入您的姓名",
    emailLabel: "Email",
    emailPh: "your@email.com",
    bodyTitle: "身體數據",
    bodyHint: "選填 · 便於預估尺寸",
    heightLabel: "身高",
    weightLabel: "體重",
    chestLabel: "胸圍",
    waistLabel: "腰圍",
    hipLabel: "臀圍",
    shoeLabel: "鞋碼",
    socialLabel: "任意平台可以聯繫到您的帳號（如：Bilibili QQ X...）",
    socialPh: "請輸入您的社群平台帳號",
    agreeText: "我已閱讀並同意購買協議",
    btnSubmit: "提 交",
    submitting: "提交中…",
    errName: "請輸入姓名",
    errEmail: "請輸入有效的電子郵件地址",
    errAgree: "請先閱讀並同意購買協議",
    doneTitle: "購買成功",
    doneText: "我們將於工作日9:00-17:00回覆報價，並與您進行接下來的溝通",
    orderCodePrefix: "您的訂單代碼：",
    queryLink: "查詢進度",
    editBanner: "編輯模式：儲存修改後，將同步至使用者可見的掉落介面",
    editAdd: "+ 新增掉落",
    editExit: "退出編輯",
    editTitle: "掉落標題",
    editPrice: "價格（RMB）",
    editStatus: "掉落狀態",
    editIncludes: "包含內容",
    editCopyright: "版權說明",
    editDelivery: "交付說明",
    editDescription: "介紹資訊",
    editUpload: "上傳圖片",
    editUploading: "上傳中…",
    editUploadHint: "JPEG / PNG / GIF / WebP",
    editSave: "儲存修改",
    editDelete: "刪除",
    editCancel: "取消",
    editLabel: "編輯",
    copyBtn: "複製訂單代碼",
    copied: "已複製 ✓",
    editConfirmDelete: "確定刪除此掉落嗎？刪除後會立即從前端掉落介面消失，此操作無法復原。",
    editSaveSuccess: "儲存成功，掉落介面已同步更新",
    editDeleteSuccess: "刪除成功",
    editImageRequired: "請上傳介紹圖片",
    editTitleRequired: "請填寫掉落標題",
    editPriceInvalid: "請填寫有效價格",
    focusTip: "焦點：點擊下方圖片選擇角色所在區域",
    noPermission: "無編輯權限，僅管理員可編輯掉落資訊",
  },
  entries: {
    shop: {
      kicker: "03 / PRE-ORDER DROPS",
      title: "線上商店",
      titleEn: "Web Shop",
      desc: "預設獸裝定期掉落販售，現貨與預售同步開放。無需漫長等待，遇見即是緣分。",
      features: ["預設獸裝掉落購買", "現貨與預售同步", "工作室直寄 · 全程可查"],
      cta: "進入商店",
      href: "/?tab=shop",
    },
    check: {
      kicker: "04 / ORDER TRACKING",
      title: "查詢",
      titleEn: "Check",
      desc: "輸入訂單編號與電子郵件，隨時查看委託進度、留言溝通與售後記錄。",
      features: ["訂單進度即時查詢", "留言與售後溝通", "附件與設定圖回顧"],
      cta: "查詢訂單",
      href: "/?tab=check",
    },
    about: {
      kicker: "05 / ACCOUNT",
      title: "關於",
      titleEn: "About",
      desc: "管理你的個人資料、歷史委託與通知設定。",
      features: ["個人資料管理", "歷史訂單彙整", "通知與安全設定"],
      cta: "龍塢圖鑑",
      href: "/gallery",
      secondaryCta: "毛布取色器",
      secondaryHref: "/sampler",
      headAction: { label: "加入我們", href: "mailto:hello@longwoo.studio" },
      joinDesc: "透過下方管道找到龍塢，一起加入我們的社群吧。",
      joinClose: "關閉",
    },
  },
  bubble: {
    signupEn: "Sign up",
    signupZh: "登入/註冊",
    langLabel: "語言",
    langTip: "切換語言",
    notifLabel: "站內信",
    notifEmpty: "暫無通知",
    notifLoginHint: "登入後可查看站內信",
    readAll: "全部已讀",
    viewOrder: "查看訂單",
    markReadFail: "操作失敗，請重試",
    loadFail: "載入失敗",
    retry: "重試",
    close: "關閉",
    logout: "登出",
    loggingOut: "登出中…",
    adminPanel: "管理後台",
    profileBtn: "個人中心",
  },
};
