/**
 * KO_COPY — LongWoo 퍼슈트 커스텀 공식 사이트 홈(new-home) 한국어 카피
 *
 * 용어 기준(i18n-quality-baseline.md 및 기존 zh/en 블록에 대응):
 * - 퍼슈트(fursuit), 커미션(위탁 커스텀 주문), 주문(order),
 *   드롭/드롭 판매(정기 한정 판매), 온라인 스토어(웹숍), 알림(회원 알림함),
 *   마이페이지(프로필), 관리자 패널(admin), 아바타(프로필 이미지),
 *   퍼 원단(인조 모피 원단), 색상 추출(컬러 샘플러), 프리오더(예약 판매)
 * - UI 문장은 공식 웹문어인 합쇼체(~합니다/~입니다/~드리겠습니다)를 사용하고,
 *   지시·요청은 '~해 주시기 바랍니다'로 통일(친근한 해요체 '~해요/~주세요' 지양)
 * - 순수 영문 브랜드·섹션 문구(kicker) 및 En 접미 영어 부라벨(heroTitleEn/titleEn 등)은
 *   zh 블록과 동일한 영문 원문을 그대로 유지(번역하지 않음)
 * - {name} / {msg} 등 플레이스홀더는 원형 그대로 보존하며, 문장 안 인용부호는
 *   한글 따옴표 “ ” 를 사용(치환 대상 이름 뒤의 조사는 “을(를)” 형태로 보완)
 * - AI 캐릭터 음성·대화 예시(예: 인사말 샘플)는 캐릭터가 직접 말하는 문장이므로
 *   역할에 맞는 자연스러운 존댓말로 유지(UI 공식문구와 구분)
 */
import type { Gt2Copy } from "./copy";

export const KO_COPY: Gt2Copy = {
  tabs: { agent: "에이전트", fursuit: "퍼슈트", shop: "스토어", check: "조회", about: "소개" },
  agent: {
    kicker: "LONGWOO · CHARACTER LAB",
    heroTitle: "나만의 캐릭터 만들기",
    heroTitleEn: "Create Your Character",
    heroLines: [
      "설정 이미지를 올리고 캐릭터의 성격을 알려 주면, 나만의 전용 AI 캐릭터를 무료로 만들 수 있습니다.",
      "오래도록 함께하며 학습하다 보면, AI의 마음은 실제 인격에 한없이 가까워질 수 있습니다.",
      "충분히 학습된 AI 캐릭터는 미래에 실제 퍼슈트에 담아 함께할 수 있게 될 것입니다.",
    ],
    uploadBtn: "만들기 시작",
    newRole: "새 캐릭터",
    send: "보내기",
    formTitle: "캐릭터 설정",
    formTitleEn: "Character Profile",
    avatarHint: "클릭하여 아바타 업로드 · JPEG / PNG / GIF / WebP · ≤ 2MB",
    avatarFallback: "아바타",
    changeAvatar: "아바타 변경",
    nameLabel: "이름",
    namePh: "캐릭터의 이름을 지어 주시기 바랍니다",
    nicknameLabel: "호칭",
    nicknamePh: "AI가 당신을 부르는 호칭입니다",
    personaLabel: "페르소나",
    personaPh: "캐릭터의 성격, 경험, 말투를 자유롭게 입력해 주시기 바랍니다…",
    toneLabel: "말투",
    tonePh: "직접 입력하거나 아래 프리셋을 선택해 주시기 바랍니다",
    greetingLabel: "인사말",
    greetingPh: "처음 만났을 때 캐릭터가 건넬 첫 마디입니다",
    createBtn: "캐릭터 만들기",
    creating: "만드는 중…",
    backBtn: "뒤로",
    errName: "캐릭터 이름을 먼저 정해 주시기 바랍니다",
    errAvatarLarge: "아바타 이미지는 2MB를 초과할 수 없습니다",
    errAvatarFormat: "JPEG / PNG / GIF / WebP 형식만 지원됩니다",
    errCreate: "만들기에 실패했습니다. 잠시 후 다시 시도해 주시기 바랍니다",
    errNetwork: "네트워크 오류가 발생했습니다. 잠시 후 다시 시도해 주시기 바랍니다",
    loginHint: "캐릭터를 만들려면 먼저 로그인이 필요합니다",
    loginPromptText: "캐릭터를 만들려면 로그인이 필요합니다. 작성하던 초안은 저장되어 있으니, 로그인하면 자동으로 이어서 만들 수 있습니다.",
    goLogin: "로그인하기",
    keepEdit: "계속 편집하기",
    tonePresets: ["다정한", "발랄한", "츤데레", "시크한", "유머러스한", "귀여운", "차분한", "열정적인", "독설가", "활기찬", "나른한", "신비로운"],
    chatMy: "내 캐릭터",
    chatEmpty: "아직 캐릭터가 없습니다. 첫 번째 캐릭터를 만들어 보시기 바랍니다",
    chatCreateFirst: "만들러 가기",
    chatHello: "대화를 시작해 보시기 바랍니다",
    chatHelloWithName: "대화를 시작해 보시기 바랍니다 · 당신을 “{name}”이라고 부릅니다",
    chatInputPh: "하고 싶은 말을 입력해 보시기 바랍니다…",
    chatClearTitle: "대화 지우기",
    chatClearConfirm: "이 캐릭터와의 모든 대화 기록을 정말 삭제하시겠습니까?",
    errChatLoad: "캐릭터를 불러오지 못했습니다. 잠시 후 다시 시도해 주시기 바랍니다",
    errChatSend: "전송에 실패했습니다. 잠시 후 다시 시도해 주시기 바랍니다",
    errChatClear: "지우지 못했습니다. 다시 시도해 주시기 바랍니다",
    editBtn: "설정 수정",
    editTitle: "캐릭터 수정",
    editTitleEn: "Edit Character",
    editSubtitle: "설정을 조정해 캐릭터를 언제든 새롭게 바꿀 수 있습니다",
    editDelete: "캐릭터 삭제",
    editDeleting: "삭제 중…",
    editSave: "저장",
    editSaving: "저장 중…",
    editDeleteConfirm: "캐릭터 “{name}”을(를) 삭제하시겠습니까? 모든 대화 기록도 함께 삭제되며, 이 작업은 되돌릴 수 없습니다.",
    errEditSave: "저장에 실패했습니다. 잠시 후 다시 시도해 주시기 바랍니다",
    errEditDelete: "삭제에 실패했습니다. 잠시 후 다시 시도해 주시기 바랍니다",
    errAvatarUpload: "아바타 업로드에 실패했습니다. 다시 시도해 주시기 바랍니다",
  },
  fursuit: {
    kicker: "COMMISSION · FULL CUSTOM",
    title: "퍼슈트 커미션 신청하기",
    titleEn: "Commission Your Fursuit",
    steps: ["설정 이미지 업로드", "옵션 선택", "혜택 선택", "연락처", "견적 대기"],
    deliveryHint: "약 4-6주 후 배송 예정*",
    priceRangeHint: "최초 주문 가격은 15000RMB-25000RMB 구간으로 계산됩니다",
    uploadTitle: "설정 이미지 업로드",
    uploadHint: "이미지는 20M 이하여야 합니다",
    reupload: "다시 업로드",
    remove: "제거",
    addonMicro: "옵션 · ADD-ON",
    addonHint: "복수 선택 가능 · 선택한 옵션은 견적에 포함됩니다",
    addonNone: "없음",
    addons: [
      { name: "휴대용 헤드백", nameEn: "Head Bag", price: "RMB 300", value: 300 },
      { name: "실내용 발", nameEn: "Indoor Feet", price: "RMB 750", value: 750 },
      { name: "Longwoo Vision 시각 보강 키트", nameEn: "Vision Kit", price: "RMB 8,888", value: 8888, disabled: true, tag: "미출시" },
    ],
    benefitTitle: "3단계: 트레이드인 또는 재구매 혜택을 선택해 주시기 바랍니다",
    benefits: [
      { label: "사용 안 함", labelEn: "None", price: "RMB 0", value: 0 },
      { label: "4년 트레이드인 혜택", labelEn: "4-Year Trade-in", price: "-RMB 3,000", value: 3000 },
      { label: "재구매 혜택*", labelEn: "Repurchase*", price: "-RMB 2,000", value: 2000 },
    ],
    benefitNote: "*이전 Xiangshan Studio 시절의 첫 커미션 고객에게도 재구매 혜택이 동일하게 적용됩니다",
    priceBase: "기본 가격",
    priceAddon: "추가 옵션",
    priceDiscount: "할인",
    priceTotal: "합계",
    contactTitle: "4단계: 신체 정보와 연락처를 입력해 주시기 바랍니다",
    bodyTitle: "신체 정보",
    bodyHint: "키 / 몸무게는 필수 · 나머지는 선택 · 사이즈 예측에 도움이 됩니다",
    socialLabel: "어느 플랫폼이든 연락 가능한 계정 (예: Bilibili QQ X...)",
    socialPh: "소셜 플랫폼 계정을 입력해 주시기 바랍니다",
    nameLabel: "이름",
    namePh: "이름을 입력해 주시기 바랍니다",
    emailLabel: "이메일",
    emailPh: "your@email.com",
    dims: [
      { key: "height", label: "키", unit: "cm" },
      { key: "weight", label: "몸무게", unit: "kg" },
      { key: "chest", label: "가슴둘레", unit: "cm" },
      { key: "waist", label: "허리둘레", unit: "cm" },
      { key: "hip", label: "엉덩이둘레", unit: "cm" },
      { key: "shoe", label: "신발 사이즈", unit: "" },
    ],
    btnPrev: "이전",
    btnNext: "다음",
    submitBtn: "제출",
    submitting: "제출 중…",
    submitHint: "제출하시면 수작업으로 견적을 낸 뒤 빠르게 연락드리겠습니다",
    doneTitle: "5단계: 견적 회신을 기다려 주시기 바랍니다",
    doneText: "평일 9:00-17:00 사이에 답변을 드리고, 이후 필요한 안내를 이어 가겠습니다",
    orderCodePrefix: "주문 코드: ",
    copyBtn: "주문 코드 복사",
    copied: "복사됨 ✓",
    queryLink: "진행 상황 조회하기",
    saveTip: "주문 코드를 잘 보관해 주시기 바랍니다. 이후 견적과 진행 상황을 조회할 때 필요합니다",
    errImgRequired: "설정 이미지를 먼저 업로드해 주시기 바랍니다",
    errImgType: "이미지 파일만 지원됩니다",
    errImgLarge: "이미지는 20MB를 초과할 수 없습니다",
    errName: "이름을 입력해 주시기 바랍니다",
    errEmail: "유효한 이메일 주소를 입력해 주시기 바랍니다",
    errDimRequired: "이 항목이 입력되지 않았습니다",
    errSubmit: "제출에 실패했습니다. 잠시 후 다시 시도해 주시기 바랍니다",
    errNetwork: "네트워크 오류가 발생했습니다. 잠시 후 다시 시도해 주시기 바랍니다",
    errUploadAlert: "설정 이미지 업로드에 실패했습니다: {msg}. 파일명은 주문과 함께 저장되어 있습니다. 나중에 로그인하여 마이페이지에서 설정 이미지를 보충하거나, 고객센터에 업로드를 요청해 주시기 바랍니다.",
  },
  checkPanel: {
    orderNoLabel: "커미션 주문번호",
    orderNoPh: "예: LW20250101001",
    emailLabel: "이메일",
    emailPh: "커미션 신청 시 입력한 이메일을 입력해 주시기 바랍니다",
    btn: "커미션 조회",
    loading: "조회 중…",
    errOrderNoRequired: "커미션 주문번호를 입력해 주시기 바랍니다",
    errEmailRequired: "이메일을 입력해 주시기 바랍니다",
    errEmailInvalid: "유효한 이메일 주소를 입력해 주시기 바랍니다",
    errQueryFailed: "조회에 실패했습니다. 주문번호와 이메일이 맞는지 확인해 주시기 바랍니다",
    errQueryUnknown: "조회 중 알 수 없는 오류가 발생했습니다. 잠시 후 다시 시도해 주시기 바랍니다",
    customerName: "고객 이름",
    phone: "연락처",
    email: "이메일",
    serviceType: "서비스 유형",
    notSpecified: "지정되지 않음",
    desc: "요청 사항",
    designImage: "설정 이미지",
    designImageMissing: "설정 이미지 업로드가 완료되지 않았습니다. 문의 사항이 있으면 고객센터로 연락해 주시기 바랍니다",
    estimateAmount: "견적 금액",
    note: "메모: ",
    deliveryLink: "배송 링크",
    replies: "답변 기록",
    createdAt: "접수 시간",
    agreeEstimate: "견적 동의",
    agreeEstimateDesc: "견적 금액을 확인해 주시기 바랍니다. 동의하시면 스튜디오에서 커미션 작업을 시작하겠습니다.",
    agreeEstimateConfirm: "이 견적에 동의하시겠습니까? 동의하시면 스튜디오에서 빠르게 주문을 받아 제작을 시작하겠습니다.",
    agreeSuccess: "견적이 확정되었습니다. 스튜디오에서 주문을 접수하여 제작을 시작할 예정입니다",
    agreeFailed: "확인에 실패했습니다. 잠시 후 다시 시도해 주시기 바랍니다",
    agreeWaiting: "견적을 확정하셨습니다. 스튜디오가 주문을 접수하면 제작이 시작되며, 진행 상황 업데이트를 확인해 주시기 바랍니다.",
    status: {
      pending: "견적 대기",
      estimated: "견적 완료",
      agreed: "견적 확정",
      accepted: "작업 접수",
      rejected: "접수 거절",
      processing: "제작 중",
      delivered: "배송 완료",
      completed: "완료",
    },
  },
  shopPanel: {
    dropsEntryKicker: "01",
    dropsEntryTitle: "퍼슈트 드롭",
    dropsEntryTitleEn: "DROP FURSUITS",
    dropsEntryDesc: "기성 퍼슈트가 정기적으로 드롭되며, 현물과 프리오더가 함께 열립니다. 오래 기다릴 필요가 없습니다. 마음에 드는 아이를 만난다면 그것이 바로 인연입니다.",
    dropsEntryCta: "드롭 보러 가기",
    peripheryEntryKicker: "02",
    peripheryEntryTitle: "LongWoo 굿즈",
    peripheryEntryTitleEn: "LONGWOO MERCH",
    peripheryEntryDesc: "굿즈 상품을 준비 중입니다. 기대해 주시기 바랍니다.",
    peripheryEntryCta: "준비 중",
    backEntries: "스토어로 돌아가기",
    dropsKicker: "01 / DROP ITEMS",
    dropsHeading: "퍼슈트 드롭",
    dropsSub: "완성분은 즉시 배송되고, 나머지는 약 4-6주 후 배송 예정입니다*",
    loading: "드롭 정보를 불러오는 중…",
    empty: "아직 드롭 정보가 없습니다. 기대해 주시기 바랍니다",
    statusOnSale: "판매 중",
    statusPreparing: "준비 중",
    statusAdopted: "입양 완료",
    statusOptionOnSale: "판매 중 (구매 가능)",
    statusOptionPreparing: "준비 중 (보기 전용)",
    statusOptionAdopted: "입양 완료 (전달 중)",
    btnSelect: "선택",
    btnAdopted: "입양 완료",
    btnPreparing: "준비 중 · 기대해 주시기 바랍니다",
    viewImage: "전체 이미지 보기",
    checkoutKicker: "02 / CHECKOUT",
    checkoutTitle: "구매 확정",
    productLabel: "선택한 드롭",
    nameLabel: "이름",
    namePh: "이름을 입력해 주시기 바랍니다",
    emailLabel: "이메일",
    emailPh: "your@email.com",
    bodyTitle: "신체 정보",
    bodyHint: "선택 입력 · 사이즈 예측에 도움이 됩니다",
    heightLabel: "키",
    weightLabel: "몸무게",
    chestLabel: "가슴둘레",
    waistLabel: "허리둘레",
    hipLabel: "엉덩이둘레",
    shoeLabel: "신발 사이즈",
    socialLabel: "어느 플랫폼이든 연락 가능한 계정 (예: Bilibili QQ X...)",
    socialPh: "소셜 플랫폼 계정을 입력해 주시기 바랍니다",
    agreeText: "구매 약관을 읽었으며 이에 동의합니다",
    btnSubmit: "제출",
    submitting: "제출 중…",
    errName: "이름을 입력해 주시기 바랍니다",
    errEmail: "유효한 이메일 주소를 입력해 주시기 바랍니다",
    errAgree: "구매 약관을 먼저 읽고 동의해 주시기 바랍니다",
    doneTitle: "구매 완료",
    doneText: "평일 9:00-17:00 사이에 답변을 드리고, 이후 필요한 안내를 이어 가겠습니다",
    orderCodePrefix: "주문 코드: ",
    queryLink: "진행 상황 조회하기",
    editBanner: "편집 모드: 저장하면 사용자에게 노출되는 드롭 화면에도 동기화됩니다",
    editAdd: "+ 드롭 추가",
    editExit: "편집 나가기",
    editTitle: "드롭 제목",
    editPrice: "가격 (RMB)",
    editStatus: "드롭 상태",
    editIncludes: "포함 내역",
    editCopyright: "저작권 안내",
    editDelivery: "배송 안내",
    editDescription: "상세 소개",
    editUpload: "이미지 업로드",
    editUploading: "업로드 중…",
    editUploadHint: "JPEG / PNG / GIF / WebP",
    editSave: "변경 사항 저장",
    editDelete: "삭제",
    editCancel: "취소",
    editLabel: "편집",
    copyBtn: "주문 코드 복사",
    copied: "복사됨 ✓",
    editConfirmDelete: "이 드롭을 삭제하시겠습니까? 삭제하면 즉시 드롭 화면에서 사라지며 되돌릴 수 없습니다.",
    editSaveSuccess: "저장되었습니다. 드롭 화면에도 반영되었습니다",
    editDeleteSuccess: "삭제되었습니다",
    editImageRequired: "소개 이미지를 업로드해 주시기 바랍니다",
    editTitleRequired: "드롭 제목을 입력해 주시기 바랍니다",
    editPriceInvalid: "유효한 가격을 입력해 주시기 바랍니다",
    focusTip: "초점: 아래 이미지를 클릭해 캐릭터가 있는 영역을 선택해 주시기 바랍니다",
    noPermission: "편집 권한이 없습니다. 관리자만 드롭 정보를 수정할 수 있습니다",
  },
  entries: {
    shop: {
      kicker: "03 / PRE-ORDER DROPS",
      title: "온라인 스토어",
      titleEn: "Web Shop",
      desc: "기성 퍼슈트가 정기적으로 드롭되며, 현물과 프리오더가 함께 열립니다. 오래 기다릴 필요가 없습니다. 마음에 드는 아이를 만난다면 그것이 바로 인연입니다.",
      features: ["기성 퍼슈트 드롭 구매", "현물과 프리오더 동시 진행", "스튜디오 직배송 · 전 과정 조회 가능"],
      cta: "스토어 들어가기",
      href: "/?tab=shop",
    },
    check: {
      kicker: "04 / ORDER TRACKING",
      title: "조회",
      titleEn: "Check",
      desc: "주문번호와 이메일을 입력해 커미션 진행 상황, 메시지 소통, A/S 기록을 언제든 확인할 수 있습니다.",
      features: ["주문 진행 상황 실시간 조회", "메시지와 A/S 상담", "첨부 파일 · 설정 이미지 다시 보기"],
      cta: "주문 조회하기",
      href: "/?tab=check",
    },
    about: {
      kicker: "05 / ABOUT",
      title: "소개",
      titleEn: "About",
      desc: "LongWoo 소개: 작품 도감, 퍼 원단 색상 추출과 커뮤니티를 여기에서 시작하세요.",
      features: ["작품 도감", "퍼 원단 색상 추출", "커뮤니티 참여"],
      cta: "LongWoo 도감",
      href: "/gallery",
      secondaryCta: "퍼 원단 색상 추출",
      secondaryHref: "/sampler",
      headAction: { label: "참여하기", href: "mailto:hello@longwoo.studio" },
      joinDesc: "아래 채널에서 LongWoo를 찾아 커뮤니티에 참여해 보세요.",
      joinClose: "닫기",
    },
  },
  bubble: {
    signupEn: "Sign up",
    signupZh: "로그인 / 회원가입",
    langLabel: "언어",
    langTip: "언어 전환",
    notifLabel: "알림",
    notifEmpty: "알림이 없습니다",
    notifLoginHint: "로그인하면 알림을 확인할 수 있습니다",
    readAll: "모두 읽음",
    viewOrder: "주문 보기",
    markReadFail: "처리하지 못했습니다. 다시 시도해 주시기 바랍니다",
    loadFail: "불러오기 실패",
    retry: "다시 시도",
    close: "닫기",
    logout: "로그아웃",
    loggingOut: "로그아웃 중…",
    adminPanel: "관리자 패널",
    profileBtn: "마이페이지",
  },
};
