import type { Gt2Copy } from "./copy";

/**
 * LongWoo ファースーツ受注サイト トップページ — 日本語（ja）用コピー定義
 *
 * ./copy.ts の zh 言語ブロック（Gt2Copy 型）とフィールド単位で完全に対応する。
 * トップレベルキー順: tabs → agent → fursuit → checkPanel → shopPanel → entries → bubble
 * 入れ子構造・配列の順序・要素数は zh ブロックと一致させる（一つも増減させない）。
 *
 * 用語方針（i18n-quality-baseline.md 準拠）:
 * - 固定訳: ファースーツ / コミッション / 注文 / ドロップ販売 / オンラインストア /
 *   お知らせ（站内信）/ マイページ / 管理画面 / アイコン / ファー生地（動物の毛皮と
 *   誤解されない表現）/ カラー抽出（取色器）
 * - 丁寧語: 説明文・案内文は「です・ます」調、ボタン類は簡潔な形で統一。
 * - ブランド・デザイン用語（kicker の LONGWOO シリーズ文言、01〜05 など）と
 *   「*En」サブフィールド（heroTitleEn / titleEn / formTitleEn / editTitleEn /
 *   dropsEntryTitleEn / peripheryEntryTitleEn / nameEn / labelEn / signupEn）は
 *   zh ブロックと同じ原文のまま維持する。
 * - {name} / {msg} プレースホルダは書き換えず、周辺文言のみ翻訳（引用符は「」）。
 * - 数字・単位（cm/kg/RMB/2MB/20M/4-6週間/9:00-17:00 等）・href・value/disabled・
 *   配列順は zh と同一。
 */
export const JA_COPY: Gt2Copy = {
  tabs: { agent: "エージェント", fursuit: "ファースーツ", shop: "ストア", check: "照会", about: "工房紹介" },
  agent: {
    kicker: "LONGWOO · CHARACTER LAB",
    heroTitle: "あなたのキャラクターを作成しましょう",
    heroTitleEn: "Create Your Character",
    heroLines: [
      "設定画像をアップロードしてキャラクターの個性を入力するだけで、あなた専用のキャラクターAIを無料で生成できます。",
      "長く共に学び、共に過ごすほど、AIはより豊かな知性を身につけ、限りなくリアルな存在へと近づいていきます。",
      "十分に育成されたAIキャラクターを、将来、実物のファースーツに搭載することも可能になります。",
    ],
    uploadBtn: "アップロード",
    formTitle: "キャラクター設定",
    formTitleEn: "Character Profile",
    avatarHint: "クリックしてアイコンをアップロード · JPEG / PNG / GIF / WebP · ≤ 2MB",
    avatarFallback: "アイコン",
    changeAvatar: "アイコンを変更",
    nameLabel: "名前",
    namePh: "その子の名前を決めてあげてください",
    nicknameLabel: "あなたの呼び名",
    nicknamePh: "AIはこの名前であなたを呼びます",
    personaLabel: "ペルソナ",
    personaPh: "その子の性格・経歴・話し方などを入力してください",
    toneLabel: "口調",
    tonePh: "自由入力、またはプリセットから選択できます",
    greetingLabel: "最初のひとこと",
    greetingPh: "その子があなたにかける最初の言葉",
    createBtn: "キャラクターを作成",
    creating: "作成中…",
    backBtn: "戻る",
    errName: "先にキャラクターの名前を決めてください",
    errAvatarLarge: "アイコン画像は2MB以下にしてください",
    errAvatarFormat: "対応形式は JPEG / PNG / GIF / WebP のみです",
    errCreate: "作成に失敗しました。時間をおいて再度お試しください",
    errNetwork: "ネットワークエラーが発生しました。時間をおいて再度お試しください",
    loginHint: "キャラクターの作成にはログインが必要です",
    loginPromptText: "キャラクターの作成にはログインが必要です。入力中の内容は下書きとして保存されているため、ログイン後に自動で復元されます",
    goLogin: "ログインする",
    keepEdit: "編集を続ける",
    tonePresets: ["おだやか", "明るい", "ツンデレ", "クール", "ユーモア", "かわいい", "落ち着いた", "情熱的", "毒舌", "元気", "のんびり", "神秘的"],
    chatMy: "マイキャラクター",
    chatEmpty: "まだキャラクターがいません。最初のキャラクターを作成しましょう",
    chatCreateFirst: "作成する",
    chatHello: "その子に話しかけてみましょう",
    chatHelloWithName: "その子に話しかけてみましょう · あなたのことは「{name}」と呼んでくれます",
    chatInputPh: "その子に何か話しかけてみましょう…",
    chatClearTitle: "会話をクリア",
    chatClearConfirm: "このキャラクターとの会話履歴をすべてクリアしますか？",
    errChatLoad: "キャラクターの読み込みに失敗しました。時間をおいて再度お試しください",
    errChatSend: "送信に失敗しました。時間をおいて再度お試しください",
    errChatClear: "クリアに失敗しました。もう一度お試しください",
    editBtn: "設定を調整",
    editTitle: "キャラクターを編集",
    editTitleEn: "Edit Character",
    editSubtitle: "設定はいつでも調整できます。気分に合わせて、新しいその子に出会えます",
    editDelete: "キャラクターを削除",
    editDeleting: "削除中…",
    editSave: "保存",
    editSaving: "保存中…",
    editDeleteConfirm: "キャラクター「{name}」を削除しますか？その子との会話履歴もすべて削除され、この操作は元に戻せません。",
    errEditSave: "保存に失敗しました。時間をおいて再度お試しください",
    errEditDelete: "削除に失敗しました。時間をおいて再度お試しください",
    errAvatarUpload: "アイコンのアップロードに失敗しました。もう一度お試しください",
  },
  fursuit: {
    kicker: "COMMISSION · FULL CUSTOM",
    title: "あなたのファースーツをコミッションしましょう",
    titleEn: "Commission Your Fursuit",
    steps: ["設定画像のアップロード", "オプションの選択", "特典の選択", "連絡先の入力", "見積もり待ち"],
    deliveryHint: "約4-6週間後の納品予定*",
    priceRangeHint: "初回のご依頼価格は15000RMB-25000RMBを目安に算出します",
    uploadTitle: "設定画像をアップロード",
    uploadHint: "画像サイズは20Mまで",
    reupload: "アップロードし直す",
    remove: "削除",
    addonMicro: "オプション · ADD-ON",
    addonHint: "複数選択可 · 選択した内容はお見積りに含まれます",
    addonNone: "なし",
    addons: [
      { name: "持ち運び用ヘッドバッグ", nameEn: "Head Bag", price: "RMB 300", value: 300 },
      { name: "室内用フィート", nameEn: "Indoor Feet", price: "RMB 750", value: 750 },
      { name: "Longwoo Vision 視覚拡張キット", nameEn: "Vision Kit", price: "RMB 8,888", value: 8888, disabled: true, tag: "未リリース" },
    ],
    benefitTitle: "ステップ3：下取り特典とリピート購入特典を利用しますか？",
    benefits: [
      { label: "利用しない", labelEn: "None", price: "RMB 0", value: 0 },
      { label: "4年間の下取り特典", labelEn: "4-Year Trade-in", price: "-RMB 3,000", value: 3000 },
      { label: "リピート購入特典*", labelEn: "Repurchase*", price: "-RMB 2,000", value: 2000 },
    ],
    benefitNote: "*旧Xiangshan Studioで初回にご依頼いただいた方も、リピート購入特典が適用されます",
    priceBase: "基本価格",
    priceAddon: "オプション",
    priceDiscount: "特典割引",
    priceTotal: "合計",
    contactTitle: "ステップ4：身体データと連絡先を入力してください",
    bodyTitle: "身体データ",
    bodyHint: "身長・体重は必須 · その他は任意 · サイズの参考にします",
    socialLabel: "ご連絡の取れるSNSアカウント（例：Bilibili QQ X...）",
    socialPh: "SNSアカウントを入力してください",
    nameLabel: "お名前",
    namePh: "お名前を入力してください",
    emailLabel: "メールアドレス",
    emailPh: "your@email.com",
    dims: [
      { key: "height", label: "身長", unit: "cm" },
      { key: "weight", label: "体重", unit: "kg" },
      { key: "chest", label: "バスト", unit: "cm" },
      { key: "waist", label: "ウエスト", unit: "cm" },
      { key: "hip", label: "ヒップ", unit: "cm" },
      { key: "shoe", label: "シューズサイズ", unit: "" },
    ],
    btnPrev: "前へ",
    btnNext: "次へ",
    submitBtn: "送信",
    submitting: "送信中…",
    submitHint: "送信後、スタッフが手作業でお見積りを作成し、できるだけ早くご連絡いたします",
    doneTitle: "ステップ5：手作業によるお見積りをお待ちください",
    doneText: "営業日の9:00-17:00にお見積りをご返信し、その後のやり取りを進めさせていただきます",
    orderCodePrefix: "ご注文コード：",
    copyBtn: "注文コードをコピー",
    copied: "コピーしました ✓",
    queryLink: "進捗を確認する",
    saveTip: "注文コードは大切に保管してください。お見積りや進捗の確認に必要です",
    errImgRequired: "設定画像をアップロードしてください",
    errImgType: "対応しているのは画像ファイルのみです",
    errImgLarge: "画像は20MB以下にしてください",
    errName: "お名前を入力してください",
    errEmail: "有効なメールアドレスを入力してください",
    errDimRequired: "この項目が未入力です",
    errSubmit: "送信に失敗しました。時間をおいて再度お試しください",
    errNetwork: "ネットワークエラーが発生しました。時間をおいて再度お試しください",
    errUploadAlert: "設定画像のアップロードに失敗しました：{msg}。ファイル名は注文とともに保存されています。後ほどマイページから設定画像を追加いただくか、サポートまでご連絡ください。",
  },
  checkPanel: {
    orderNoLabel: "注文番号",
    orderNoPh: "例：LW20250101001",
    emailLabel: "メールアドレス",
    emailPh: "コミッション申込時に入力したメールアドレスを入力してください",
    btn: "照会する",
    loading: "照会中…",
    errOrderNoRequired: "注文番号を入力してください",
    errEmailRequired: "メールアドレスを入力してください",
    errEmailInvalid: "有効なメールアドレスを入力してください",
    errQueryFailed: "照会に失敗しました。注文番号とメールアドレスをご確認ください",
    errQueryUnknown: "照会中に不明なエラーが発生しました。時間をおいて再度お試しください",
    customerName: "お客様名",
    phone: "電話番号",
    email: "メールアドレス",
    serviceType: "サービス種別",
    notSpecified: "指定なし",
    desc: "ご要望内容",
    designImage: "設定画像",
    designImageMissing: "設定画像のアップロードが完了していません。ご不明な場合はサポートへお問い合わせください",
    estimateAmount: "お見積り金額",
    note: "備考：",
    deliveryLink: "納品リンク",
    replies: "返信履歴",
    createdAt: "作成日時",
    agreeEstimate: "見積りに同意する",
    agreeEstimateDesc: "お見積り金額をご確認ください。同意後、スタジオがコミッションの対応を開始します。",
    agreeEstimateConfirm: "このお見積りに同意しますか？同意後、スタジオがすみやかに受注して制作を開始します。",
    agreeSuccess: "お見積りを確認しました。スタジオがすみやかに制作を開始します",
    agreeFailed: "確認に失敗しました。時間をおいて再度お試しください",
    agreeWaiting: "お見積りは確認済みです。スタジオが受注した後に制作を開始しますので、進捗の更新をご確認ください。",
    status: {
      pending: "見積り待ち",
      estimated: "見積り済み",
      agreed: "見積り同意済み",
      accepted: "受注済み",
      rejected: "受注辞退",
      processing: "制作中",
      delivered: "納品済み",
      completed: "完了",
    },
  },
  shopPanel: {
    dropsEntryKicker: "01",
    dropsEntryTitle: "ドロップ販売",
    dropsEntryTitleEn: "DROP FURSUITS",
    dropsEntryDesc: "既製のファースーツを定期的にドロップ販売。在庫品と先行予約品を同時に販売しています。長い待ち時間は不要。出会えたら、それもご縁です。",
    dropsEntryCta: "ドロップを見る",
    peripheryEntryKicker: "02",
    peripheryEntryTitle: "LongWoo グッズ",
    peripheryEntryTitleEn: "LONGWOO MERCH",
    peripheryEntryDesc: "グッズは準備中です。お楽しみに。",
    peripheryEntryCta: "準備中",
    backEntries: "ストアに戻る",
    dropsKicker: "01 / DROP ITEMS",
    dropsHeading: "ドロップ販売",
    dropsSub: "完成分はすぐに発送、残りの分は約4-6週間後に納品予定*",
    loading: "ドロップ情報を読み込み中…",
    empty: "ドロップ情報はまだありません。お楽しみに",
    statusOnSale: "販売中",
    statusPreparing: "準備中",
    statusAdopted: "売約済み",
    statusOptionOnSale: "販売中（購入可）",
    statusOptionPreparing: "準備中（閲覧のみ）",
    statusOptionAdopted: "売約済み（納品中）",
    btnSelect: "選択",
    btnAdopted: "売約済み",
    btnPreparing: "準備中 · お楽しみに",
    viewImage: "画像を大きく表示",
    checkoutKicker: "02 / CHECKOUT",
    checkoutTitle: "購入確認",
    productLabel: "選択中のドロップ",
    nameLabel: "お名前",
    namePh: "お名前を入力してください",
    emailLabel: "メールアドレス",
    emailPh: "your@email.com",
    bodyTitle: "身体データ",
    bodyHint: "任意 · サイズの参考にします",
    heightLabel: "身長",
    weightLabel: "体重",
    chestLabel: "バスト",
    waistLabel: "ウエスト",
    hipLabel: "ヒップ",
    shoeLabel: "シューズサイズ",
    socialLabel: "ご連絡の取れるSNSアカウント（例：Bilibili QQ X...）",
    socialPh: "SNSアカウントを入力してください",
    agreeText: "購入規約を読み、同意しました",
    btnSubmit: "送信",
    submitting: "送信中…",
    errName: "お名前を入力してください",
    errEmail: "有効なメールアドレスを入力してください",
    errAgree: "購入規約をお読みいただき、同意してください",
    doneTitle: "購入が完了しました",
    doneText: "営業日の9:00-17:00にお見積りをご返信し、その後のやり取りを進めさせていただきます",
    orderCodePrefix: "ご注文コード：",
    queryLink: "進捗を確認する",
    editBanner: "編集モード：変更を保存すると、公開中のドロップ一覧に反映されます",
    editAdd: "+ ドロップを追加",
    editExit: "編集を終了",
    editTitle: "タイトル",
    editPrice: "価格（RMB）",
    editStatus: "ステータス",
    editIncludes: "含まれるもの",
    editCopyright: "著作権",
    editDelivery: "納品について",
    editDescription: "紹介文",
    editUpload: "画像をアップロード",
    editUploading: "アップロード中…",
    editUploadHint: "JPEG / PNG / GIF / WebP",
    editSave: "変更を保存",
    editDelete: "削除",
    editCancel: "キャンセル",
    editLabel: "編集",
    copyBtn: "注文コードをコピー",
    copied: "コピーしました ✓",
    editConfirmDelete: "このドロップを削除しますか？削除するとすぐに公開中の一覧から消え、この操作は元に戻せません。",
    editSaveSuccess: "保存しました。公開中の一覧にも反映されています",
    editDeleteSuccess: "削除しました",
    editImageRequired: "紹介画像をアップロードしてください",
    editTitleRequired: "タイトルを入力してください",
    editPriceInvalid: "有効な価格を入力してください",
    focusTip: "フォーカス：下の画像をクリックして、キャラクターが写っている場所を選択してください",
    noPermission: "編集権限がありません。ドロップ情報の編集は管理者のみ行えます",
  },
  entries: {
    shop: {
      kicker: "03 / PRE-ORDER DROPS",
      title: "オンラインストア",
      titleEn: "Web Shop",
      desc: "既製ファースーツを定期的にドロップ販売。在庫品と先行予約を同時に販売し、長い待ち時間は不要。出会えたら、それもご縁です。",
      features: ["既製ファースーツのドロップ購入", "在庫品と先行予約の同時販売", "スタジオ直送 · 全工程を追跡可能"],
      cta: "ストアへ",
      href: "/?tab=shop",
    },
    check: {
      kicker: "04 / ORDER TRACKING",
      title: "注文照会",
      titleEn: "Check",
      desc: "注文番号とメールアドレスを入力すると、コミッションの進捗やメッセージ、アフターケアの記録をいつでも確認できます。",
      features: ["注文の進捗をリアルタイムで確認", "メッセージでの相談・アフターケア", "添付ファイルと設定画像の見直し"],
      cta: "注文を照会する",
      href: "/?tab=check",
    },
    about: {
      kicker: "05 / ACCOUNT",
      title: "工房について",
      titleEn: "About",
      desc: "プロフィールや過去のコミッション、通知設定をまとめて管理できます。",
      features: ["プロフィールの管理", "過去の注文の確認", "通知・セキュリティ設定"],
      cta: "ギャラリーを見る",
      href: "/gallery",
      secondaryCta: "ファー生地カラー抽出",
      secondaryHref: "/sampler",
    },
  },
  bubble: {
    signupEn: "Sign up",
    signupZh: "ログイン/新規登録",
    langLabel: "言語",
    langTip: "言語を切り替える",
    notifLabel: "お知らせ",
    notifEmpty: "お知らせはありません",
    notifLoginHint: "ログインするとお知らせを確認できます",
    readAll: "すべて既読にする",
    viewOrder: "注文を見る",
    markReadFail: "操作に失敗しました。もう一度お試しください",
    loadFail: "読み込みに失敗しました",
    retry: "再試行",
    close: "閉じる",
    logout: "ログアウト",
    loggingOut: "ログアウト中…",
    adminPanel: "管理画面",
    profileBtn: "マイページ",
  },
};
