import type { Gt2Copy } from "./copy";

/**
 * LongWoo 兽装定制站首页 — Français（fr）文案定义
 *
 * 与 ./copy.ts 的 zh 语言块（Gt2Copy 型）逐字段一一对应；
 * 顶层键顺序: tabs → agent → fursuit → checkPanel → shopPanel → entries → bubble；
 * 嵌套结构与数组逐项对应，一个字段不多不少。
 *
 * 术语取舍（依据 i18n-quality-baseline.md）:
 * - 固定译法: fursuit 保留原文；委托（定制）→ commande sur mesure / commande；
 *   订单 → commande；掉落（预设发售）→ vente drop；在线商店 → boutique en ligne；
 *   站内信/通知 → notifications；个人中心 → espace personnel；
 *   管理后台 → panneau d’administration；智能体 → agent；头像 → avatar；
 *   毛布（人造毛皮）→ tissu（配合 faux fur 语义，避免误读为动物毛皮）。
 * - 全文使用法语正式礼貌体 vouvoiement（vous / veuillez）。
 * - 字符串值内的法语撇号一律使用弯撇号 U+2019（’），禁止 ASCII 直撇号；
 *   需加引号处使用法语书名引号 « »。
 * - 品牌/设计性英文原样保留：kicker（LONGWOO · CHARACTER LAB、
 *   COMMISSION · FULL CUSTOM、01/02/03/04/05 系列）与 entries 的 kicker。
 * - 以 En 结尾的英文副标签（heroTitleEn / titleEn / formTitleEn / editTitleEn /
 *   dropsEntryTitleEn / peripheryEntryTitleEn / nameEn / labelEn / signupEn）
 *   与 zh 块英文原值完全一致，不译。
 * - 占位符 {name} / {msg} 原样保留，仅翻译周边文字。
 * - 数字、单位（cm/kg/RMB/JPG/PNG/GIF/WebP/2MB/20M/15000RMB-25000RMB/
 *   300/750/8888/4-6 semaines/9:00-17:00 等）、href/secondaryHref、
 *   value/disabled 布尔值与数组顺序均与 zh 块一致。
 */
export const FR_COPY: Gt2Copy = {
  tabs: { agent: "Agent", fursuit: "Fursuit", shop: "Boutique", check: "Suivi", about: "À propos" },
  agent: {
    kicker: "LONGWOO · CHARACTER LAB",
    heroTitle: "Créez votre personnage",
    heroTitleEn: "Create Your Character",
    heroLines: [
      "Téléversez la planche de référence de votre personnage, décrivez sa personnalité et générez gratuitement votre propre IA de personnage.",
      "Avec un apprentissage et une compagnie au long cours, l’esprit de l’IA se rapproche indéfiniment d’un état authentique.",
      "Une IA de personnage pleinement entraînée pourra, à l’avenir, être chargée dans un fursuit physique.",
    ],
    uploadBtn: "Téléverser",
    formTitle: "Profil du personnage",
    formTitleEn: "Character Profile",
    avatarHint: "Cliquez pour téléverser un avatar · JPEG / PNG / GIF / WebP · ≤ 2MB",
    avatarFallback: "Avatar",
    changeAvatar: "Changer d’avatar",
    nameLabel: "Nom",
    namePh: "Donnez-lui un nom",
    nicknameLabel: "Votre surnom",
    nicknamePh: "C’est ainsi que l’IA vous appellera",
    personaLabel: "Personnalité",
    personaPh: "Décrivez sa personnalité, son histoire et sa façon de parler…",
    toneLabel: "Ton",
    tonePh: "Choisissez un préréglage ou personnalisez le ton",
    greetingLabel: "Premier message",
    greetingPh: "La première phrase que votre personnage vous adresse",
    createBtn: "Créer le personnage",
    creating: "Création…",
    backBtn: "Retour",
    errName: "Veuillez d’abord donner un nom à votre personnage",
    errAvatarLarge: "L’avatar ne doit pas dépasser 2MB",
    errAvatarFormat: "Seuls les formats JPEG / PNG / GIF / WebP sont acceptés",
    errCreate: "La création a échoué. Veuillez réessayer plus tard.",
    errNetwork: "Erreur réseau. Veuillez réessayer plus tard.",
    loginHint: "Connectez-vous d’abord pour créer un personnage",
    loginPromptText: "La création d’un personnage nécessite une connexion. Votre brouillon est enregistré et sera restauré automatiquement après connexion.",
    goLogin: "Se connecter",
    keepEdit: "Continuer l’édition",
    tonePresets: ["Doux", "Vif", "Tsundere", "Froid", "Humoristique", "Mignon", "Posé", "Chaleureux", "Mordant", "Énergique", "Nonchalant", "Mystérieux"],
    chatMy: "Mes personnages",
    chatEmpty: "Aucun personnage pour l’instant — créez votre premier",
    chatCreateFirst: "Créer",
    chatHello: "Dites bonjour à votre personnage",
    chatHelloWithName: "Dites bonjour à votre personnage, qui vous appelle « {name} »",
    chatInputPh: "Dites-lui quelque chose…",
    chatClearTitle: "Effacer la discussion",
    chatClearConfirm: "Voulez-vous vraiment effacer tout l’historique de la discussion avec ce personnage ?",
    errChatLoad: "Le chargement du personnage a échoué. Veuillez réessayer plus tard.",
    errChatSend: "L’envoi a échoué. Veuillez réessayer plus tard.",
    errChatClear: "L’effacement a échoué. Veuillez réessayer.",
    editBtn: "Réglages",
    editTitle: "Modifier le personnage",
    editTitleEn: "Edit Character",
    editSubtitle: "Ajustez sa personnalité à tout moment — votre personnage reste comme neuf",
    editDelete: "Supprimer le personnage",
    editDeleting: "Suppression…",
    editSave: "Enregistrer",
    editSaving: "Enregistrement…",
    editDeleteConfirm: "Supprimer le personnage « {name} » ? Tout son historique de discussion sera également supprimé. Cette action est irréversible.",
    errEditSave: "La sauvegarde a échoué. Veuillez réessayer plus tard.",
    errEditDelete: "La suppression a échoué. Veuillez réessayer plus tard.",
    errAvatarUpload: "Le téléversement de l’avatar a échoué. Veuillez réessayer.",
  },
  fursuit: {
    kicker: "COMMISSION · FULL CUSTOM",
    title: "Commandez votre fursuit",
    titleEn: "Commission Your Fursuit",
    steps: ["Référence", "Options", "Avantages", "Contact", "Estimation"],
    deliveryHint: "Livraison estimée sous 4-6 semaines*",
    priceRangeHint: "Le prix d’une première commande est calculé selon une fourchette de 15000RMB-25000RMB",
    uploadTitle: "Téléverser la planche de référence",
    uploadHint: "L’image ne doit pas dépasser 20M",
    reupload: "Re-téléverser",
    remove: "Retirer",
    addonMicro: "Options · ADD-ON",
    addonHint: "Choix multiple · les options sélectionnées sont incluses dans l’estimation",
    addonNone: "Aucun",
    addons: [
      { name: "Sac de tête", nameEn: "Head Bag", price: "RMB 300", value: 300 },
      { name: "Pattes d’intérieur", nameEn: "Indoor Feet", price: "RMB 750", value: 750 },
      { name: "Longwoo Vision — kit d’amélioration visuelle", nameEn: "Vision Kit", price: "RMB 8,888", value: 8888, disabled: true, tag: "Bientôt disponible" },
    ],
    benefitTitle: "Étape 3 : souhaitez-vous faire valoir une reprise ou un réachat ?",
    benefits: [
      { label: "Aucun", labelEn: "None", price: "RMB 0", value: 0 },
      { label: "Reprise sur 4 ans", labelEn: "4-Year Trade-in", price: "-RMB 3,000", value: 3000 },
      { label: "Avantage réachat*", labelEn: "Repurchase*", price: "-RMB 2,000", value: 2000 },
    ],
    benefitNote: "*Les premiers clients de l’ancien studio Xiangshan bénéficient également de l’avantage de réachat",
    priceBase: "Prix de base",
    priceAddon: "Options",
    priceDiscount: "Remise",
    priceTotal: "Total",
    contactTitle: "Étape 4 : vos mensurations et vos coordonnées",
    bodyTitle: "Mensurations",
    bodyHint: "Taille et poids obligatoires · autres champs facultatifs · pour estimer les tailles",
    socialLabel: "Un compte sur lequel nous pouvons vous joindre (ex. : Bilibili, QQ, X…)",
    socialPh: "Saisissez votre compte de réseau social",
    nameLabel: "Nom",
    namePh: "Saisissez votre nom",
    emailLabel: "E-mail",
    emailPh: "votre@email.com",
    dims: [
      { key: "height", label: "Taille", unit: "cm" },
      { key: "weight", label: "Poids", unit: "kg" },
      { key: "chest", label: "Tour de poitrine", unit: "cm" },
      { key: "waist", label: "Tour de taille", unit: "cm" },
      { key: "hip", label: "Tour de hanches", unit: "cm" },
      { key: "shoe", label: "Pointure", unit: "" },
    ],
    btnPrev: "Précédent",
    btnNext: "Suivant",
    submitBtn: "Envoyer",
    submitting: "Envoi…",
    submitHint: "Après l’envoi, nous établirons une estimation manuelle et vous recontacterons rapidement.",
    doneTitle: "Étape 5 : en attente de notre estimation manuelle",
    doneText: "Nous vous répondrons avec un devis et poursuivrons les échanges les jours ouvrés de 9:00-17:00",
    orderCodePrefix: "Votre code de commande : ",
    copyBtn: "Copier le code de commande",
    copied: "Copié ✓",
    queryLink: "Suivre la commande",
    saveTip: "Conservez précieusement ce code de commande pour suivre plus tard votre estimation et son avancement",
    errImgRequired: "Veuillez d’abord téléverser la planche de référence",
    errImgType: "Seuls les fichiers image sont acceptés",
    errImgLarge: "L’image ne doit pas dépasser 20MB",
    errName: "Veuillez saisir votre nom",
    errEmail: "Veuillez saisir une adresse e-mail valide",
    errDimRequired: "Champ obligatoire",
    errSubmit: "L’envoi a échoué. Veuillez réessayer plus tard.",
    errNetwork: "Erreur réseau. Veuillez réessayer plus tard.",
    errUploadAlert: "Le téléversement de la planche de référence a échoué : {msg}. Le nom du fichier a été conservé avec la commande ; vous pourrez ajouter la planche plus tard depuis votre espace personnel, ou contacter le service client pour être aidé.",
  },
  checkPanel: {
    orderNoLabel: "N° de commande",
    orderNoPh: "ex. : LW20250101001",
    emailLabel: "E-mail",
    emailPh: "Saisissez l’e-mail utilisé pour passer la commande",
    btn: "Suivre ma commande",
    loading: "Recherche…",
    errOrderNoRequired: "Veuillez saisir le numéro de commande",
    errEmailRequired: "Veuillez saisir votre e-mail",
    errEmailInvalid: "Veuillez saisir une adresse e-mail valide",
    errQueryFailed: "La recherche a échoué. Vérifiez que le numéro de commande et l’e-mail sont corrects.",
    errQueryUnknown: "Une erreur inconnue est survenue. Veuillez réessayer plus tard.",
    customerName: "Nom du client",
    phone: "Téléphone",
    email: "E-mail",
    serviceType: "Type de service",
    notSpecified: "Non précisé",
    desc: "Description de la demande",
    designImage: "Planche de référence",
    designImageMissing: "La planche de référence n’a pas pu être téléversée. Pour toute question, contactez le service client.",
    estimateAmount: "Montant estimé",
    note: "Remarque : ",
    deliveryLink: "Lien de livraison",
    replies: "Réponses",
    createdAt: "Date de création",
    agreeEstimate: "Accepter l’estimation",
    agreeEstimateDesc: "Veuillez confirmer le montant estimé. Une fois votre accord donné, le studio commencera à traiter votre commande.",
    agreeEstimateConfirm: "Accepter cette estimation ? Le studio acceptera votre commande et commencera la fabrication dans les plus brefs délais.",
    agreeSuccess: "Estimation confirmée. Le studio acceptera votre commande et commencera la fabrication rapidement.",
    agreeFailed: "La confirmation a échoué. Veuillez réessayer plus tard.",
    agreeWaiting: "Vous avez confirmé l’estimation. La fabrication démarrera dès que le studio aura accepté votre commande ; suivez les mises à jour.",
    status: {
      pending: "En attente d’estimation",
      estimated: "Estimation envoyée",
      agreed: "Estimation acceptée",
      accepted: "Commande acceptée",
      rejected: "Commande refusée",
      processing: "En cours de fabrication",
      delivered: "Livrée",
      completed: "Terminée",
    },
  },
  shopPanel: {
    dropsEntryKicker: "01",
    dropsEntryTitle: "Vente drop",
    dropsEntryTitleEn: "DROP FURSUITS",
    dropsEntryDesc: "Des fursuits prédéfinis sont régulièrement mis en vente drop, en stock comme en précommande. Fini l’attente interminable : si vous craquez pour l’un d’eux, c’est le destin.",
    dropsEntryCta: "Voir les drops",
    peripheryEntryKicker: "02",
    peripheryEntryTitle: "Produits dérivés LongWoo",
    peripheryEntryTitleEn: "LONGWOO MERCH",
    peripheryEntryDesc: "La gamme de produits dérivés est en préparation. Restez à l’écoute !",
    peripheryEntryCta: "Prochainement",
    backEntries: "Retour à la boutique",
    dropsKicker: "01 / DROP ITEMS",
    dropsHeading: "Vente drop",
    dropsSub: "Les pièces finies sont livrées immédiatement · le reste sous 4-6 semaines*",
    loading: "Chargement des drops…",
    empty: "Aucun drop pour le moment. Restez à l’écoute !",
    statusOnSale: "En vente",
    statusPreparing: "En préparation",
    statusAdopted: "Adopté",
    statusOptionOnSale: "En vente (achetable)",
    statusOptionPreparing: "En préparation (consultation seule)",
    statusOptionAdopted: "Adopté (en cours de livraison)",
    btnSelect: "Choisir",
    btnAdopted: "Adopté",
    btnPreparing: "En préparation · Restez à l’écoute",
    viewImage: "Voir l’image en grand",
    checkoutKicker: "02 / CHECKOUT",
    checkoutTitle: "Confirmer l’achat",
    productLabel: "Drop sélectionné",
    nameLabel: "Nom",
    namePh: "Saisissez votre nom",
    emailLabel: "E-mail",
    emailPh: "votre@email.com",
    bodyTitle: "Mensurations",
    bodyHint: "Facultatif · pour estimer les tailles",
    heightLabel: "Taille",
    weightLabel: "Poids",
    chestLabel: "Tour de poitrine",
    waistLabel: "Tour de taille",
    hipLabel: "Tour de hanches",
    shoeLabel: "Pointure",
    socialLabel: "Un compte sur lequel nous pouvons vous joindre (ex. : Bilibili, QQ, X…)",
    socialPh: "Saisissez votre compte de réseau social",
    agreeText: "J’ai lu et j’accepte l’accord d’achat",
    btnSubmit: "Envoyer",
    submitting: "Envoi…",
    errName: "Veuillez saisir votre nom",
    errEmail: "Veuillez saisir une adresse e-mail valide",
    errAgree: "Veuillez d’abord lire et accepter l’accord d’achat",
    doneTitle: "Achat réussi !",
    doneText: "Nous vous répondrons avec un devis et poursuivrons les échanges les jours ouvrés de 9:00-17:00",
    orderCodePrefix: "Votre code de commande : ",
    queryLink: "Suivre la commande",
    editBanner: "Mode édition : après enregistrement, les modifications seront visibles sur la page publique des drops.",
    editAdd: "+ Ajouter un drop",
    editExit: "Quitter le mode édition",
    editTitle: "Titre du drop",
    editPrice: "Prix (RMB)",
    editStatus: "Statut du drop",
    editIncludes: "Contenu inclus",
    editCopyright: "Droits d’auteur",
    editDelivery: "Informations de livraison",
    editDescription: "Description",
    editUpload: "Téléverser une image",
    editUploading: "Téléversement…",
    editUploadHint: "JPEG / PNG / GIF / WebP",
    editSave: "Enregistrer les modifications",
    editDelete: "Supprimer",
    editCancel: "Annuler",
    editLabel: "Modifier",
    copyBtn: "Copier le code de commande",
    copied: "Copié ✓",
    editConfirmDelete: "Supprimer ce drop ? Il disparaîtra immédiatement de la page publique des drops. Cette action est irréversible.",
    editSaveSuccess: "Enregistrement réussi. La page publique des drops a été mise à jour.",
    editDeleteSuccess: "Suppression réussie",
    editImageRequired: "Veuillez téléverser une image",
    editTitleRequired: "Veuillez saisir le titre du drop",
    editPriceInvalid: "Veuillez saisir un prix valide",
    focusTip: "Focus : cliquez sur l’image ci-dessous pour indiquer où se trouve le personnage",
    noPermission: "Vous n’avez pas les droits d’édition. Seuls les administrateurs peuvent modifier les drops.",
  },
  entries: {
    shop: {
      kicker: "03 / PRE-ORDER DROPS",
      title: "Boutique en ligne",
      titleEn: "Web Shop",
      desc: "Des fursuits prédéfinis sont régulièrement mis en vente drop, en stock comme en précommande. Fini l’attente interminable : si vous craquez pour l’un d’eux, c’est le destin.",
      features: [
        "Achat de fursuits en vente drop",
        "En stock et en précommande",
        "Expédition directe du studio · suivi complet",
      ],
      cta: "Entrer dans la boutique",
      href: "/?tab=shop",
    },
    check: {
      kicker: "04 / ORDER TRACKING",
      title: "Suivi",
      titleEn: "Check",
      desc: "Saisissez votre numéro de commande et votre e-mail pour consulter à tout moment l’avancement de votre commande, vos échanges et l’historique après-vente.",
      features: [
        "Suivi de commande en temps réel",
        "Échanges et service après-vente",
        "Pièces jointes et planches de référence",
      ],
      cta: "Suivre ma commande",
      href: "/?tab=check",
    },
    about: {
      kicker: "05 / ACCOUNT",
      title: "À propos",
      titleEn: "About",
      desc: "Gérez votre profil, l’historique de vos commandes et vos paramètres de notifications.",
      features: [
        "Gestion du profil",
        "Historique des commandes",
        "Notifications et sécurité",
      ],
      cta: "Voir la galerie",
      href: "/gallery",
      secondaryCta: "Sélecteur de couleur du tissu",
      secondaryHref: "/sampler",
      headAction: { label: "Rejoignez-nous", href: "mailto:hello@longwoo.studio" },
      joinDesc: "Retrouvez LongWoo via les canaux ci-dessous et rejoignez notre communauté.",
      joinClose: "Fermer",
    },
  },
  bubble: {
    signupEn: "Sign up",
    signupZh: "Connexion / Inscription",
    langLabel: "Langue",
    langTip: "Changer de langue",
    notifLabel: "Notifications",
    notifEmpty: "Aucune notification",
    notifLoginHint: "Connectez-vous pour consulter vos notifications",
    readAll: "Tout marquer comme lu",
    viewOrder: "Voir ma commande",
    markReadFail: "L’opération a échoué. Veuillez réessayer.",
    loadFail: "Échec du chargement",
    retry: "Réessayer",
    close: "Fermer",
    logout: "Se déconnecter",
    loggingOut: "Déconnexion…",
    adminPanel: "Panneau d’administration",
    profileBtn: "Espace personnel",
  },
};
